version: 2.1

orbs:
  aws-s3: circleci/aws-s3@1.0.15

jobs:
  serverInstall:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: node --version
      - run: npm config set @bit:registry https://node.bitsrc.io
      - run: npm install

  autoDeploy:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: npm config set @bit:registry https://node.bitsrc.io
      - run: npm install
      - run: npm run --silent build
      - aws-s3/sync:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          aws-region: AWS_REGION
          from: dist
          to: 's3://web-prod.mindlogger.org'
          overwrite: true

workflows:
  test_all:
    jobs:
      - serverInstall
      - autoDeploy:
          requires:
            - serverInstall
          filters:
            branches:
              only: circle-ci
